// -----------------------BOOK ALLOCATIONS-----------------------------------------
// THERE ARE N NUMBER OF BOOKS EACH iTH BOOKS HAS A[i] NUMBER OF PAGES YOU HAVE TO ALLOCATE BOOKS SUCH TO M NUMBER OF STUDENTS 
// SO THAT THS MAXIMUM NO OF PAGES ALLOCATED TO  STUDENT IS MINIMUM 
//  * EACH BOOK SHOULD BE ALLOCATED TO A STUDENT 
//  * EACH STUDENT HAS TO BE ALLOCATED AT LEAST ONR BOOK 
//  * ALLOTMENT SHOULD BE IN CONTIGUOUS ORDER.
//  CALCULATE AND RETURN THE MINIMUM POSSIBLE NUMBER  